name = "Havoc Rewind"
author = "NullHarp,Dj,Adam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43785fa8811119c84845733aa922f4a33d96f2c6c582b91e905a97cf14335aaa"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
