name = "Havoc Rewind"
author = "NullHarp,Dj,Adam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c58a8a372d9e4fc0705414ba228af41ebae662c97be31be4aebc481f193ae95"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
