name = "Havoc Rewind"
author = "NullHarp,Dj,Adam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db1ed2a4be6c5ad7bbf17f56a21fd51e4e4920ca98169c3ad1fca84a8aa771c1"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
